// Generated by CoffeeScript 1.6.3
(function() {
  var https, performQueueRequest;

  https = require('https');

  performQueueRequest = function(host, username, password, cb) {
    var data, options, req;
    options = {
      host: host,
      port: 443,
      path: '/login-queue/rest/queue/authenticate',
      method: 'POST'
    };
    data = "payload=user%3D" + username + "%2Cpassword%3D" + password;
    req = https.request(options, function(res) {
      return res.on('data', function(d) {
        data = JSON.parse(d.toString('utf-8'));
        return cb(null, data);
      });
    });
    req.on('error', function(err) {
      return cb(err);
    });
    return req.end(data);
  };

  module.exports = performQueueRequest;

}).call(this);
